--1
CREATE VIEW v_products AS
SELECT PROD_SUBCATEGORY, MAX(PROD_LIST_PRICE) AS MAX
FROM SH.PRODUCTS 
GROUP BY PROD_SUBCATEGORY;

--2
CREATE VIEW v_customers AS
SELECT c.CUST_FIRST_NAME || ' ' || c.CUST_LAST_NAME AS CLIENTE, AVG(s.AMOUNT_SOLD) AS AVERAGE
FROM SH.CUSTOMERS c
INNER JOIN SH.SALES s ON c.CUST_ID = s.CUST_ID
WHERE s.TIME_ID BETWEEN TO_DATE('01/01/1998', 'DD/MM/YYYY') AND TO_DATE('31/12/1998', 'DD/MM/YYYY')
GROUP BY c.CUST_FIRST_NAME, c.CUST_LAST_NAME
HAVING AVG(s.AMOUNT_SOLD) > (
    SELECT AVG(AMOUNT_SOLD) 
    FROM SH.SALES 
    WHERE TIME_ID BETWEEN TO_DATE('01/01/1998', 'DD/MM/YYYY') 
                      AND TO_DATE('31/12/1998', 'DD/MM/YYYY')
);

--3
CREATE OR REPLACE VIEW v_scott AS
SELECT e.ENAME, e.JOB, d.DNAME, e.SAL, NVL(e.SAL + NVL(e.COMM, 0), e.SAL) AS SALARIO_TOTAL
FROM SCOTT.EMP e
INNER JOIN SCOTT.DEPT d ON e.DEPTNO = d.DEPTNO
WHERE d.LOC IN ('DALLAS', 'CHICAGO');

--4
CREATE VIEW v_employee6 AS
SELECT FUNC.FIRST_NAME AS FUNC_NAME, FUNC.SALARY, MAN.FIRST_NAME AS MAN_NAME
FROM HR.EMPLOYEES FUNC
INNER JOIN HR.EMPLOYEES MAN ON FUNC.MANAGER_ID = MAN.EMPLOYEE_ID;

--5
CREATE VIEW v_employee5 AS
SELECT e.FIRST_NAME, d.DEPARTMENT_NAME, l.CITY
FROM HR.LOCATIONS l 
INNER JOIN HR.DEPARTMENTS d ON l.LOCATION_ID = d.LOCATION_ID
    INNER JOIN HR.EMPLOYEES e ON d.MANAGER_ID = e.MANAGER_ID;

--6
CREATE OR REPLACE VIEW v_employee7 AS
SELECT e.FIRST_NAME, j.JOB_TITLE, d.DEPARTMENT_ID, d.DEPARTMENT_NAME 
FROM HR.EMPLOYEES e 
INNER JOIN HR.JOBS j ON e.JOB_ID = j.JOB_ID
    INNER JOIN HR.DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
    	INNER JOIN HR.LOCATIONS l ON d.LOCATION_ID = l.LOCATION_ID
WHERE l.CITY IN ('Tokyo', 'Roma', 'Oxford', 'Munich');

--7
CREATE VIEW v_employee8 AS
SELECT FUNC.FIRST_NAME AS FUNCIONARIO, FUNC.EMPLOYEE_ID AS NR_FUNCIONARIO, MAN.FIRST_NAME AS GERENTE, MAN.MANAGER_ID AS NR_GERENTE
FROM HR.EMPLOYEES FUNC
INNER JOIN HR.EMPLOYEES MAN ON FUNC.MANAGER_ID = MAN.EMPLOYEE_ID;

--8
CREATE VIEW v_employee9 AS
SELECT MAN.FIRST_NAME, d.DEPARTMENT_NAME, l.CITY
FROM HR.EMPLOYEES FUNC
INNER JOIN HR.EMPLOYEES MAN ON FUNC.MANAGER_ID = MAN.EMPLOYEE_ID
    INNER JOIN HR.DEPARTMENTS d ON MAN.DEPARTMENT_ID = d.DEPARTMENT_ID
    	INNER JOIN HR.LOCATIONS l ON d.LOCATION_ID = l.LOCATION_ID;

--9
CREATE VIEW v_employee10 AS
SELECT e.FIRST_NAME, e.SALARY, j.JOB_TITLE
FROM HR.EMPLOYEES e 
INNER JOIN HR.JOBS j ON e.JOB_ID = j.JOB_ID
    WHERE e.SALARY > 3850;

--10
CREATE VIEW v_employee11 AS
SELECT FIRST_NAME, SALARY
FROM HR.EMPLOYEES 
WHERE SALARY NOT BETWEEN 1500 AND 2850;

--11
CREATE VIEW v_employee12 AS
SELECT e.FIRST_NAME || ' ' || e.LAST_NAME AS FUNCIONARIO, e.SALARY AS SALARIO_MENSAL
FROM HR.EMPLOYEES e 
INNER JOIN HR.DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
    WHERE e.SALARY > 1500 AND d.DEPARTMENT_ID IN (10,30);

--12
CREATE OR REPLACE VIEW v_employee13 AS
SELECT e.FIRST_NAME, j.JOB_TITLE
FROM HR.EMPLOYEES e 
INNER JOIN HR.JOBS j ON e.JOB_ID = j.JOB_ID
    WHERE e.MANAGER_ID IS NULL;

--13
CREATE OR REPLACE VIEW v_employee14 AS
SELECT FIRST_NAME || ' ' || LAST_NAME AS FUNCIONARIO, SALARY, NVL(TO_CHAR(COMMISSION_PCT), 'Não comissionado') AS COMISSAO	
FROM HR.EMPLOYEES 

--14
CREATE OR REPLACE VIEW v_employee15 AS
SELECT FIRST_NAME || ' ' || LAST_NAME AS FUNCIONARIO
FROM HR.EMPLOYEES 
WHERE 
    (UPPER(FIRST_NAME)LIKE '%SS%' 
    OR UPPER(LAST_NAME) LIKE '%SS%' 
    AND DEPARTMENT_ID = 30) OR MANAGER_ID = 103;

--15
CREATE VIEW v_employee16 AS
SELECT e.FIRST_NAME || '' || e.LAST_NAME, e.SALARY, j.JOB_TITLE
FROM HR.EMPLOYEES e 
INNER JOIN HR.JOBS j ON e.JOB_ID = j.JOB_ID
    WHERE j.JOB_TITLE IN ('Marketing Representative', 'Marketing Manager', 'Programmer') AND e.SALARY NOT IN(1000, 3000, 5000);

--16
CREATE VIEW v_employee16 AS
SELECT d.DEPARTMENT_NAME, SUM(e.SALARY) AS SOMA
FROM HR.EMPLOYEES e 
INNER JOIN HR.DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
GROUP BY d.DEPARTMENT_NAME
HAVING SUM(e.SALARY) > 5000;

--17 
CREATE VIEW v_employee16 AS
SELECT j.JOB_TITLE, MAX(e.SALARY) AS MAIS_ALTO_POR_FUNCAO
FROM HR.EMPLOYEES e 
INNER JOIN HR.JOBS j ON e.JOB_ID = j.JOB_ID
GROUP BY j.JOB_TITLE
HAVING MAX(e.SALARY) <= 10000;

--18
CREATE VIEW v_employee16 AS
SELECT j.JOB_TITLE, AVG(e.SALARY) AS MEDIA_DE_SALARIO_POR_FUNCAO
FROM HR.EMPLOYEES e 
INNER JOIN HR.JOBS j ON e.JOB_ID = j.JOB_ID
GROUP BY j.JOB_TITLE
HAVING j.JOB_TITLE LIKE '%Manager%';

--19
CREATE VIEW v_employee16 AS
SELECT j.JOB_TITLE, AVG(e.SALARY) AS MEDIA_DE_SALARIO_POR_FUNCAO
FROM HR.EMPLOYEES e 
INNER JOIN HR.JOBS j ON e.JOB_ID = j.JOB_ID
GROUP BY j.JOB_TITLE
HAVING j.JOB_TITLE LIKE '%Manager%'
AND AVG(e.SALARY) BETWEEN 10500 AND 12500;

--20
CREATE VIEW v_employees AS
SELECT d.DEPARTMENT_NAME, COUNT(e.EMPLOYEE_ID) AS QTD
FROM HR.EMPLOYEES e
JOIN HR.DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN HR.JOBS j ON e.JOB_ID = j.JOB_ID
WHERE j.JOB_TITLE LIKE '%Manager%'
GROUP BY d.DEPARTMENT_NAME
HAVING COUNT(d.MANAGER_ID) > 1;
