--1
CREATE VIEW v_employee AS
SELECT e.*, j.JOB_TITLE
FROM HR.EMPLOYEES e 
INNER JOIN HR.JOBS j ON e.JOB_ID = j.JOB_ID
WHERE e.COMMISSION_PCT IS NOT NULL 
AND e.SALARY BETWEEN 5000 AND 7000;

--2
CREATE VIEW v_country AS
SELECT r.REGION_NAME, c.COUNTRY_NAME
FROM HR.REGIONS r INNER JOIN HR.COUNTRIES c
ON r.REGION_ID = c.REGION_ID

--3
CREATE VIEW v_department AS
SELECT d.DEPARTMENT_NAME, l.CITY, e.FIRST_NAME, e.PHONE_NUMBER
FROM HR.LOCATIONS l 
INNER JOIN HR.DEPARTMENTS d ON l.LOCATION_ID = d.LOCATION_ID
    INNER JOIN HR.EMPLOYEES e ON d.MANAGER_ID = e.MANAGER_ID;

--4
CREATE VIEW v_employee2 AS
SELECT e.FIRST_NAME, j.JOB_TITLE
FROM HR.EMPLOYEES e 
INNER JOIN HR.JOBS j ON e.JOB_ID = j.JOB_ID;

--5
CREATE VIEW v_employee3 AS
SELECT e.FIRST_NAME, j.JOB_TITLE, jh.START_DATE, jh.END_DATE
FROM HR.EMPLOYEES e 
INNER JOIN HR.JOBS j ON e.JOB_ID = j.JOB_ID
    INNER JOIN HR.JOB_HISTORY jh ON j.JOB_ID = jh.JOB_ID;