--1
CREATE OR REPLACE PROCEDURE retorna_nome(p_cod IN Pessoa.id%TYPE, p_nome OUT Pessoa.nome%TYPE) AS
BEGIN
   SELECT nome 
	INTO p_nome
    FROM Pessoa
    WHERE id = p_cod;

	EXCEPTION
        WHEN NO_DATA_FOUND THEN
        p_nome := 'Pessoa não encontrada :(';
END;

DECLARE
   p_nome Pessoa.nome%TYPE;
BEGIN
   retorna_nome(1, p_nome);
   DBMS_OUTPUT.PUT_LINE('Nome retornado: ' || p_nome);
END;

--2
CREATE OR REPLACE PROCEDURE tabuada(p_num IN NUMBER) AS
BEGIN
   FOR i IN 1..10 LOOP
      DBMS_OUTPUT.PUT_LINE(p_num || ' x ' || i || ' = ' || (p_num * i));
   END LOOP;
END;

BEGIN
   tabuada(2);  
END;

--3
CREATE OR REPLACE PROCEDURE e_bissexto AS
BEGIN
   DBMS_OUTPUT.PUT_LINE('Os seguintes anos são bissextos:');
 FOR p_ano IN 2000..2100 LOOP
   IF (MOD(p_ano,4) = 0 AND MOD(p_ano,100) != 0) OR (MOD(p_ano,400) = 0) THEN
     DBMS_OUTPUT.PUT_LINE(p_ano);
   END IF;
 END LOOP;
END;

EXEC e_bissexto()

--4
CREATE OR REPLACE PROCEDURE CALCULA_MEDIA (NR_MATRICULA NUMBER, NOME VARCHAR2, A1 NUMBER, A2 NUMBER, A3 NUMBER, A4 NUMBER) 
IS
 V_MAIOR NUMBER(3,1);
 V_MEDIA NUMBER(3,1);
 V_RESULTADO VARCHAR2(15);
BEGIN
 IF A1 > A2 THEN V_MAIOR := A1;
 ELSE V_MAIOR := A2;
 END IF;
 
 V_MEDIA := (V_MAIOR + A3 + A4)/3;

 IF V_MEDIA < 6 THEN V_RESULTADO := 'REPROVADO';
 ELSE V_RESULTADO := 'APROVADO';
 END IF;
 
 INSERT INTO ALUNO VALUES (NR_MATRICULA,NOME,A1,A2,A3,A4,V_MEDIA,V_RESULTADO);
END CALCULA_MEDIA;

BEGIN
   CALCULA_MEDIA (123, 'Ana', 9 , 10, 8, 6);  
END;

select*from aluno

--5
CREATE OR REPLACE PROCEDURE CALCULA_BONUS (P_ANO LUCRO.ANO%TYPE, P_MAT SALARIO.MATRICULA%TYPE) 
IS
 V_VL_LUCRO LUCRO.VALOR%TYPE;
V_VL_SALARIO SALARIO.SALARIO%TYPE;
 V_BONUS NUMBER(7,2);
BEGIN
 SELECT VALOR INTO V_VL_LUCRO FROM LUCRO
 WHERE ANO = P_ANO;
 
SELECT SALARIO INTO V_VL_SALARIO FROM SALARIO
WHERE MATRICULA = P_MAT;

 V_BONUS := V_VL_LUCRO * 0.01 + V_VL_SALARIO * 0.05;

 DBMS_OUTPUT.PUT_LINE ('Valor do Bonus: ' || V_BONUS);
END;

EXEC CALCULA_BONUS (2020,1001);